account/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from django.views import generic

from . import views as acc_views

app_name="account"

urlpatterns = [
    path("register/", acc_views.CreateUserView.as_view(), name="register"),
    path("login/", auth_views.LoginView.as_view(template_name="account/login.html"), name="login"),
    path("logout/", auth_views.LogoutView.as_view(template_name="account/logout.html"), name="logout"),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace="main")),
    path('account/', include('account.urls', namespace="account")),
] + static(
    settings.MEDIA_URL, 
    document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from . import views

app_name="main"

urlpatterns =[
    path("", views.HomeView.as_view(), name="home"),
    path("profile/", views.ProfileView.as_view(), name="profile"),
]

account/models.py
from django.db import models

# Create your models here.

main/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.
class Website(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="websites")
    title = models.CharField(max_length=100)
    filepath = models.FileField(blank=True, upload_to="projects/")

main/forms.py
from django import forms


CHOICES = [('webpage', 'Webpage'), ('website', 'Website')]

class CloneForm(forms.Form):
    option = forms.CharField(widget=forms.Select(choices=CHOICES))
    url = forms.CharField(max_length=250)
    project_name = forms.CharField(max_length=100)

account/views.py
from django.shortcuts import render
from django.views import generic
from django.contrib import messages
from django.urls import reverse
from django.shortcuts import redirect
from django.http import HttpResponse
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

# Create your views here.
class CreateUserView(generic.CreateView):
  template_name="account/register.html"
  form_class=UserCreationForm
  model=User 
  
  def form_valid(self, form):
    user = form.save(commit=False)
    user.set_password(user.password)
    user.save()
    return super(CreateUserView, self).form_valid(form) 
  
  def get_success_url(self):
    return reverse("login")

main/views.py
from django.shortcuts import render
from django.views import generic
from django.http import HttpResponse
from django.core.files import File
from pathlib import Path
from django.conf import settings

import os

from .copier import Clone
from .forms import CloneForm
from .models import Website

# Create your views here.
class HomeView(generic.TemplateView):
    template_name = "main/home.html"
    
    extra_context = {"form": CloneForm(),}
    
    def post(self, *args, **kwargs):
        url = self.request.POST.get("url")
        project_name = self.request.POST.get("project_name")
        option = self.request.POST.get("option")
        
        try:
            clone = Clone(url, project_name)
            if option == "webpage":
                filepath = Path(clone.page())
            else:
                filepath = Path(clone.website())
            new = Website.objects.create(
                user = self.request.user,
                title = project_name)
            with filepath.open(mode='rb') as f:
                new.filepath = File(f, name=filepath.name)
                new.save()
            
            if os.path.exists(f"{settings.BASE_DIR}/{project_name}.zip"):
                os.remove(f"{settings.BASE_DIR}/{project_name}.zip")
            
            context = {"new": new}
            return render(self.request, "main/download.html", context)
        except:
            return HttpResponse("Unable to clone")


class ProfileView(generic.ListView):
    model = Website 
    template_name = "main/profile.html"
    context_object_name = "projects" 
    
    def get_queryset(self, *args, **kwargs):
        return super().get_queryset(*args, **kwargs).filter(user=self.request.user)

main/templates/main/download.html
<div class="justify-content-center">
    <a href="{{new.filepath.url}}" class="btn btn-primary">Download</a>
</div>

main/templates/main/home.html
{% extends "base.html" %}

{% block content %}
{% if request.user.is_authenticated %}
    {% include "main/partials/clone.html" %}
{% else %}
    {% include "main/partials/landing_page.html" %}
{% endif %}
{% endblock %}

main/templates/main/partials/clone.html
{% load crispy_forms_tags %}
{% load django_htmx %}

    <br>
    <legend>
        <h1>Clone Webpage/Website with ease</h1>
    </legend>
    <hr>
    <br>
    <form 
        hx-post="{% url "main:home" %}" 
        hx-target="#outcome" 
        hx-swap="innerHTML" 
        hx-indicator="#indicator"
    >
        {% csrf_token %}
        {{ form|crispy }}
        <br>
        <input type="submit" value="Submit" class="btn btn-secondary">
    </form>
    <br>
    <div id="outcome" class="text-center"></div>
    
    <div class="spinner-grow htmx-indicator" role="status" id="indicator">
      <span class="visually-hidden">Loading...</span>
    </div>

main/templates/main/partials/landing_page.html
{% load static %}

<div class="container-fluid d-flex align-items-center justify-content-center" style="height: 100vh;" id="landing_page"> <!-- we added an id -->

  <div class= "content m-0 text-center mw-full h-full">
    <h1 class="text-secondary" style="font-size:50px;">
         Copiar
    </h1> 
    <p> Clone website/webpaga with ease </p>
    <!-- we changed this button -->
    <a href="{% url 'account:login' %}" class="btn btn-secondary mt-10">Start</a>
  </div>
</div>

main/templates/main/profile.html
{% extends "base.html" %} 
{% load crispy_forms_tags %} 
{% block content %}
<br />
<legend>
  <h1>{{ request.user.user }} Profile</h1>
</legend>
<hr />
<br />
{% if projects %}
<table class="table">
  <thead class="thead-dark">
    <tr>
      <th scope="col">#</th>
      <th colspan="2">Title</th>
      <th>Link</th>
    </tr>
  </thead>
  <tbody>
    {% for proj in projects %}
    <tr>
      <th scope="row">{{ forloop.counter }}</th>
      <th colspan="2">{{ proj.title }}</th>
      <th>
          <a href="{{proj.filepath.url}}" class="btn btn-primary">Download</a>
      </th>
    </tr>
    {% endfor %}
  </tbody>
</table>
{% else %}
<p>No saved websites/webpage</p>
{% endif %} 
{% endblock %}

templates/base.html
<!DOCTYPE html>
{% load static %}
{% load django_htmx %}
{% load crispy_forms_tags %}

<html>
  <head>
    <meta http-equiv="content-type" content="text/html; charset=utf-8" />
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
    <title>
      {% block title %}Copiar {% endblock %}
    </title>
    <style>
        .htmx-indicator{
            display:none;
        }
        .htmx-request .my-indicator{
            display:inline;
        }
        .htmx-request.my-indicator{
            display:inline;
        }
    </style>
  </head>
  <body hx-headers='{"X-CSRFToken": "{{ csrf_token }}"}'>
    <!-- As a heading -->
    {% include "nav.html" %}
    
    <div class="container">
      {% block content %}
      {% endblock %}
    </div>
    
    <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'htmx/htmx.min.js' %}"></script>
    <script src="{% static 'htmx/django-htmx.js' %}"></script>
    <script src="{% static 'htmx/hyperscript.js' %}"></script>
  </body>
</html>

templates/nav.html
<nav class="navbar navbar-expand-md navbar-dark bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="/">Copiar</a>
    <ul class="navbar-nav justify-content-end">
        {% if request.user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="/">{{ request.user.username }}</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url "main:profile" %}">Profile</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url "account:logout" %}">Logout</a>
        </li>
        {% else %}
        <li class="nav-item">
          <a class="nav-link" href="{% url "account:login" %}">Login</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url "account:register" %}">Register</a>
        </li>
        {% endif %}
      </ul>
  </div>
</nav>